import "./globals.css"

import { ReactNode } from "react"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { NavBar } from "@/src/components"

import AuthProvider from "./auth/AuthProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Codeguy's NextApp",
  description: "Generated by create next app",
}

const navLinks = [
  { href: "/", label: "Home" },
  { href: "/users", label: "Users" },
  { href: "/products", label: "Products" },
  { href: "/admin", label: "Admin" },
  { href: "/upload", label: "Upload" },
]

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <AuthProvider>
          <NavBar navLinks={navLinks} ariaLabel="Main" />
          <main className="p-5"> {children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
