import "./globals.css"

import { ReactNode } from "react"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Header } from "@/src/components"

import AuthProvider from "./authProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Codeguy's NextApp",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <main className="p-5"> {children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
